### ISSUE TITLE
Problems with setup.sh

### ISSUE THREAD

**Issue by Cibertus** [programa-stic/marvin-django#1]
Hello, 

I'm having problems executing the setup.sh script. It is failing when it tries to execute manage.py file. The error being displayed is:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/**init**.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/**init**.py", line 354, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/**init**.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 87, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/**init**.py", line 37, in import_module
    **import**(name)
ImportError: No module named preferences
Django superuser creation:
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/**init**.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/**init**.py", line 354, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/**init**.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 87, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/**init**.py", line 37, in import_module
    **import**(name)
ImportError: No module named preferences

Could you please tell me what is going on?

Thank you.

**Comment by jheguia** [comment]
Hi Cibertus,
   Please confirm the file marvin-django/marvin/marvin/settings.py is present. You should previously have edited it as stated in the README_en.md file, as well as marvin-django/marvin/frontpage/settings.py.

Cheers,
   Juan
